Update unit.yaml

diff --git a/.github/workflows/unit.yaml b/.github/workflows/unit.yaml
--- a/.github/workflows/unit.yaml
+++ b/.github/workflows/unit.yaml
@@ -12,25 +12,26 @@ env:
 jobs:
   rwde-build-and-test:
     # if: contains(github.event.pull_request.title, 'UT')
+    if: ${{ contains(github.event.pull_request.title, 'ut') }}
     # Latest Ubuntu supporting Python 3.9.5 is 20.04
     environment: dmi-databricks-qa2-workspace
     runs-on: ubuntu-20.04
     steps:
-      - name: Set PR title as output
-        id: pr
-        run: |
-          echo "::set-output name=title::${{ github.event.pull_request.title }}"
+      # - name: Set PR title as output
+      #   id: pr
+      #   run: |
+      #     echo "::set-output name=title::${{ github.event.pull_request.title }}"
           
-      - name: Check PR title for UT
-        id: check
-        run: |
-          TITLE="${{ steps.pr.outputs.title }}"
-          if [[ "$TITLE" == *"UT"* ]]; then
-            echo "UT found in PR title."
-          else
-            echo "UT not found in PR title. Exiting."
-            exit 1
-          fi
+      # - name: Check PR title for UT
+      #   id: check
+      #   run: |
+      #     TITLE="${{ steps.pr.outputs.title }}"
+      #     if [[ "$TITLE" == *"UT"* ]]; then
+      #       echo "UT found in PR title."
+      #     else
+      #       echo "UT not found in PR title. Exiting."
+      #       exit 1
+      #     fi
           
       - name: Checkout Source Code
         uses: actions/checkout@v3
